// Generated by tools/icons/generate_icons.py — do not edit by hand.
// Icons: Lucide (ISC), Tabler Icons (MIT).
package com.macrotracker.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

/**
 * The app's single icon set. Line icons use a 2px stroke on a 24px grid, so
 * they stay consistent at every size; tint them with `Icon(tint = …)`.
 */
object AppIcons {
    /** Lucide `circle-user` */
    val Account: ImageVector by lazy { icon("Account") { s("M2 12 a10 10 0 1 0 20 0 a10 10 0 1 0 -20 0"); s("M9 10 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0"); s("M7 20.662 V19 a2 2 0 0 1 2 -2 h6 a2 2 0 0 1 2 2 v1.662") } }
    /** Lucide `activity` */
    val Activity: ImageVector by lazy { icon("Activity") { s("M22 12 h-2.48 a2 2 0 0 0 -1.93 1.46 l-2.35 8.36 a0.25 0.25 0 0 1 -0.48 0 L9.24 2.18 a0.25 0.25 0 0 0 -0.48 0 l-2.35 8.36 A2 2 0 0 1 4.49 12 H2") } }
    /** Lucide `plus` */
    val Add: ImageVector by lazy { icon("Add") { s("M5 12 h14"); s("M12 5 v14") } }
    /** Lucide `circle-plus` */
    val AddCircle: ImageVector by lazy { icon("AddCircle") { s("M2 12 a10 10 0 1 0 20 0 a10 10 0 1 0 -20 0"); s("M8 12 h8"); s("M12 8 v8") } }
    /** Lucide `arrow-left` */
    val ArrowBack: ImageVector by lazy { icon("ArrowBack") { s("m12 19 l-7 -7 l7 -7"); s("M19 12 H5") } }
    /** Lucide `arrow-down` */
    val ArrowDown: ImageVector by lazy { icon("ArrowDown") { s("M12 5 v14"); s("m19 12 l-7 7 l-7 -7") } }
    /** Lucide `arrow-up` */
    val ArrowUp: ImageVector by lazy { icon("ArrowUp") { s("m5 12 l7 -7 l7 7"); s("M12 19 V5") } }
    /** Lucide `bed` */
    val Bed: ImageVector by lazy { icon("Bed") { s("M2 4 v16"); s("M2 8 h18 a2 2 0 0 1 2 2 v10"); s("M2 17 h20"); s("M6 8 v9") } }
    /** Lucide `bell` */
    val Bell: ImageVector by lazy { icon("Bell") { s("M10.268 21 a2 2 0 0 0 3.464 0"); s("M3.262 15.326 A1 1 0 0 0 4 17 h16 a1 1 0 0 0 0.74 -1.673 C19.41 13.956 18 12.499 18 8 A6 6 0 0 0 6 8 c0 4.499 -1.411 5.956 -2.738 7.326") } }
    /** Lucide `bike` */
    val Bike: ImageVector by lazy { icon("Bike") { s("M15 17.5 a3.5 3.5 0 1 0 7 0 a3.5 3.5 0 1 0 -7 0"); s("M2 17.5 a3.5 3.5 0 1 0 7 0 a3.5 3.5 0 1 0 -7 0"); s("M14 5 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0"); s("M12 17.5 V14 l-3 -3 l4 -3 l2 3 h2") } }
    /** Lucide `blocks` */
    val Blocks: ImageVector by lazy { icon("Blocks") { s("M10 22 V7 a1 1 0 0 0 -1 -1 H4 a2 2 0 0 0 -2 2 v12 a2 2 0 0 0 2 2 h12 a2 2 0 0 0 2 -2 v-5 a1 1 0 0 0 -1 -1 H2"); s("M15 2 h6 a1 1 0 0 1 1 1 v6 a1 1 0 0 1 -1 1 h-6 a1 1 0 0 1 -1 -1 v-6 a1 1 0 0 1 1 -1 z") } }
    /** Lucide `zap` */
    val Bolt: ImageVector by lazy { icon("Bolt") { s("M15.914 4 a1.5 1.5 0 0 0 -2.474 -1.561 l-9 9 A1.5 1.5 0 0 0 5.5 14 h4.002 a0.5 0.5 0 0 1 0.471 0.666 L8.086 20 a1.5 1.5 0 0 0 2.475 1.56 l9 -9 A1.5 1.5 0 0 0 18.5 10 h-3.997 a0.5 0.5 0 0 1 -0.472 -0.667 z") } }
    /** Lucide `zap-off` */
    val BoltOff: ImageVector by lazy { icon("BoltOff") { s("M10.768 5.111 L13.44 2.44 a1.5 1.5 0 0 1 2.474 1.561 l-1.633 4.625"); s("m18.889 13.232 l0.672 -0.672 A1.5 1.5 0 0 0 18.5 10 h-2.844"); s("m2 2 l20 20"); s("m7.94 7.94 l-3.5 3.499 A1.5 1.5 0 0 0 5.5 14 h4.002 a0.5 0.5 0 0 1 0.471 0.666 L8.086 20 a1.5 1.5 0 0 0 2.475 1.56 l5.5 -5.5") } }
    /** Lucide `bot` */
    val Bot: ImageVector by lazy { icon("Bot") { s("M12 8 V4 H8"); s("M6 8 h12 a2 2 0 0 1 2 2 v8 a2 2 0 0 1 -2 2 h-12 a2 2 0 0 1 -2 -2 v-8 a2 2 0 0 1 2 -2 z"); s("M2 14 h2"); s("M20 14 h2"); s("M15 13 v2"); s("M9 13 v2") } }
    /** Lucide `calendar` */
    val Calendar: ImageVector by lazy { icon("Calendar") { s("M8 2 v3"); s("M16 2 v3"); s("M5 3 h14 a2 2 0 0 1 2 2 v14 a2 2 0 0 1 -2 2 h-14 a2 2 0 0 1 -2 -2 v-14 a2 2 0 0 1 2 -2 z"); s("M3 9 h18") } }
    /** Lucide `calendar-days` */
    val CalendarDays: ImageVector by lazy { icon("CalendarDays") { s("M8 2 v3"); s("M16 2 v3"); s("M5 3 h14 a2 2 0 0 1 2 2 v14 a2 2 0 0 1 -2 2 h-14 a2 2 0 0 1 -2 -2 v-14 a2 2 0 0 1 2 -2 z"); s("M3 9 h18"); s("M8 13 h0.01"); s("M12 13 h0.01"); s("M16 13 h0.01"); s("M8 17 h0.01"); s("M12 17 h0.01"); s("M16 17 h0.01") } }
    /** Lucide `camera` */
    val Camera: ImageVector by lazy { icon("Camera") { s("M13.997 4 a2 2 0 0 1 1.76 1.05 l0.486 0.9 A2 2 0 0 0 18.003 7 H20 a2 2 0 0 1 2 2 v9 a2 2 0 0 1 -2 2 H4 a2 2 0 0 1 -2 -2 V9 a2 2 0 0 1 2 -2 h1.997 a2 2 0 0 0 1.759 -1.048 l0.489 -0.904 A2 2 0 0 1 10.004 4 z"); s("M9 13 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0") } }
    /** Lucide `chart-column` */
    val ChartBar: ImageVector by lazy { icon("ChartBar") { s("M3 3 v16 a2 2 0 0 0 2 2 h16"); s("M18 17 V9"); s("M13 17 V5"); s("M8 17 v-3") } }
    /** Lucide `chart-line` */
    val ChartLine: ImageVector by lazy { icon("ChartLine") { s("M3 3 v16 a2 2 0 0 0 2 2 h16"); s("m19 9 l-5 5 l-4 -4 l-3 3") } }
    /** Lucide `chart-pie` */
    val ChartPie: ImageVector by lazy { icon("ChartPie") { s("M21 12 c0.552 0 1.005 -0.449 0.95 -0.998 a10 10 0 0 0 -8.953 -8.951 c-0.55 -0.055 -0.998 0.398 -0.998 0.95 v8 a1 1 0 0 0 1 1 z"); s("M21.21 15.89 A10 10 0 1 1 8 2.83") } }
    /** Lucide `message-circle` */
    val Chat: ImageVector by lazy { icon("Chat") { s("M2.992 16.342 a2 2 0 0 1 0.094 1.167 l-1.065 3.29 a1 1 0 0 0 1.236 1.168 l3.413 -0.998 a2 2 0 0 1 1.099 0.092 a10 10 0 1 0 -4.777 -4.719") } }
    /** Lucide `check` */
    val Check: ImageVector by lazy { icon("Check") { s("M20 6 L9 17 l-5 -5") } }
    /** Lucide `circle-check` */
    val CheckCircle: ImageVector by lazy { icon("CheckCircle") { s("M2 12 a10 10 0 1 0 20 0 a10 10 0 1 0 -20 0"); s("m16 9 l-5.5 5.5 L8 12") } }
    /** Tabler `circle-check` (filled) */
    val CheckCircleFilled: ImageVector by lazy { icon("CheckCircleFilled") { f("M17 3.34 a10 10 0 1 1 -14.995 8.984 l-0.005 -0.324 l0.005 -0.324 a10 10 0 0 1 14.995 -8.336 z m-1.293 5.953 a1 1 0 0 0 -1.32 -0.083 l-0.094 0.083 l-3.293 3.292 l-1.293 -1.292 l-0.094 -0.083 a1 1 0 0 0 -1.403 1.403 l0.083 0.094 l2 2 l0.094 0.083 a1 1 0 0 0 1.226 0 l0.094 -0.083 l4 -4 l0.083 -0.094 a1 1 0 0 0 -0.083 -1.32 z") } }
    /** Lucide `chevron-down` */
    val ChevronDown: ImageVector by lazy { icon("ChevronDown") { s("m6 9 l6 6 l6 -6") } }
    /** Lucide `chevron-left` */
    val ChevronLeft: ImageVector by lazy { icon("ChevronLeft") { s("m15 18 l-6 -6 l6 -6") } }
    /** Lucide `chevron-right` */
    val ChevronRight: ImageVector by lazy { icon("ChevronRight") { s("m9 18 l6 -6 l-6 -6") } }
    /** Lucide `chevron-up` */
    val ChevronUp: ImageVector by lazy { icon("ChevronUp") { s("m18 15 l-6 -6 l-6 6") } }
    /** Lucide `clock` */
    val Clock: ImageVector by lazy { icon("Clock") { s("M2 12 a10 10 0 1 0 20 0 a10 10 0 1 0 -20 0"); s("M12 6 v6 l4 2") } }
    /** Lucide `x` */
    val Close: ImageVector by lazy { icon("Close") { s("M18 6 L6 18"); s("m6 6 l12 12") } }
    /** Lucide `cloud` */
    val Cloud: ImageVector by lazy { icon("Cloud") { s("M17.5 19 H9 a7 7 0 1 1 6.71 -9 h1.79 a4.5 4.5 0 1 1 0 9 Z") } }
    /** Lucide `code` */
    val Code: ImageVector by lazy { icon("Code") { s("m16 18 l6 -6 l-6 -6"); s("m8 6 l-6 6 l6 6") } }
    /** Lucide `copy` */
    val Copy: ImageVector by lazy { icon("Copy") { s("M10 8 h10 a2 2 0 0 1 2 2 v10 a2 2 0 0 1 -2 2 h-10 a2 2 0 0 1 -2 -2 v-10 a2 2 0 0 1 2 -2 z"); s("M4 16 c-1.1 0 -2 -0.9 -2 -2 V4 c0 -1.1 0.9 -2 2 -2 h10 c1.1 0 2 0.9 2 2") } }
    /** Lucide `cpu` */
    val Cpu: ImageVector by lazy { icon("Cpu") { s("M12 20 v2"); s("M12 2 v2"); s("M17 20 v2"); s("M17 2 v2"); s("M2 12 h2"); s("M2 17 h2"); s("M2 7 h2"); s("M20 12 h2"); s("M20 17 h2"); s("M20 7 h2"); s("M7 20 v2"); s("M7 2 v2"); s("M6 4 h12 a2 2 0 0 1 2 2 v12 a2 2 0 0 1 -2 2 h-12 a2 2 0 0 1 -2 -2 v-12 a2 2 0 0 1 2 -2 z"); s("M9 8 h6 a1 1 0 0 1 1 1 v6 a1 1 0 0 1 -1 1 h-6 a1 1 0 0 1 -1 -1 v-6 a1 1 0 0 1 1 -1 z") } }
    /** Lucide `layout-dashboard` */
    val Dashboard: ImageVector by lazy { icon("Dashboard") { s("M4 3 h5 a1 1 0 0 1 1 1 v7 a1 1 0 0 1 -1 1 h-5 a1 1 0 0 1 -1 -1 v-7 a1 1 0 0 1 1 -1 z"); s("M15 3 h5 a1 1 0 0 1 1 1 v3 a1 1 0 0 1 -1 1 h-5 a1 1 0 0 1 -1 -1 v-3 a1 1 0 0 1 1 -1 z"); s("M15 12 h5 a1 1 0 0 1 1 1 v7 a1 1 0 0 1 -1 1 h-5 a1 1 0 0 1 -1 -1 v-7 a1 1 0 0 1 1 -1 z"); s("M4 16 h5 a1 1 0 0 1 1 1 v3 a1 1 0 0 1 -1 1 h-5 a1 1 0 0 1 -1 -1 v-3 a1 1 0 0 1 1 -1 z") } }
    /** Lucide `trash` */
    val Delete: ImageVector by lazy { icon("Delete") { s("M10 11 v6"); s("M14 11 v6"); s("M19 6 v14 a2 2 0 0 1 -2 2 H7 a2 2 0 0 1 -2 -2 V6"); s("M3 6 h18"); s("M8 6 V4 a2 2 0 0 1 2 -2 h4 a2 2 0 0 1 2 2 v2") } }
    /** Lucide `download` */
    val Download: ImageVector by lazy { icon("Download") { s("M12 15 V3"); s("M21 15 v4 a2 2 0 0 1 -2 2 H5 a2 2 0 0 1 -2 -2 v-4"); s("m7 10 l5 5 l5 -5") } }
    /** Lucide `dumbbell` */
    val Dumbbell: ImageVector by lazy { icon("Dumbbell") { s("M17.596 12.768 a2 2 0 1 0 2.829 -2.829 l-1.768 -1.767 a2 2 0 0 0 2.828 -2.829 l-2.828 -2.828 a2 2 0 0 0 -2.829 2.828 l-1.767 -1.768 a2 2 0 1 0 -2.829 2.829 z"); s("m2.5 21.5 l1.4 -1.4"); s("m20.1 3.9 l1.4 -1.4"); s("M5.343 21.485 a2 2 0 1 0 2.829 -2.828 l1.767 1.768 a2 2 0 1 0 2.829 -2.829 l-6.364 -6.364 a2 2 0 1 0 -2.829 2.829 l1.768 1.767 a2 2 0 0 0 -2.828 2.829 z"); s("m9.6 14.4 l4.8 -4.8") } }
    /** Lucide `pencil` */
    val Edit: ImageVector by lazy { icon("Edit") { s("M21.174 6.812 a1 1 0 0 0 -3.986 -3.987 L3.842 16.174 a2 2 0 0 0 -0.5 0.83 l-1.321 4.352 a0.5 0.5 0 0 0 0.623 0.622 l4.353 -1.32 a2 2 0 0 0 0.83 -0.497 z"); s("m15 5 l4 4") } }
    /** Lucide `external-link` */
    val ExternalLink: ImageVector by lazy { icon("ExternalLink") { s("M15 3 h6 v6"); s("M10 14 L21 3"); s("M18 13 v6 a2 2 0 0 1 -2 2 H5 a2 2 0 0 1 -2 -2 V8 a2 2 0 0 1 2 -2 h6") } }
    /** Lucide `eye` */
    val Eye: ImageVector by lazy { icon("Eye") { s("M2.062 12.348 a1 1 0 0 1 0 -0.696 a10.75 10.75 0 0 1 19.876 0 a1 1 0 0 1 0 0.696 a10.75 10.75 0 0 1 -19.876 0"); s("M9 12 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0") } }
    /** Lucide `eye-off` */
    val EyeOff: ImageVector by lazy { icon("EyeOff") { s("M10.733 5.076 a10.744 10.744 0 0 1 11.205 6.575 a1 1 0 0 1 0 0.696 a10.747 10.747 0 0 1 -1.444 2.49"); s("M14.084 14.158 a3 3 0 0 1 -4.242 -4.242"); s("M17.479 17.499 a10.75 10.75 0 0 1 -15.417 -5.151 a1 1 0 0 1 0 -0.696 a10.75 10.75 0 0 1 4.446 -5.143"); s("m2 2 l20 20") } }
    /** Lucide `flag` */
    val Flag: ImageVector by lazy { icon("Flag") { s("M4 22 V4 a1 1 0 0 1 0.4 -0.8 A6 6 0 0 1 8 2 c3 0 5 2 7.333 2 q2 0 3.067 -0.8 A1 1 0 0 1 20 4 v10 a1 1 0 0 1 -0.4 0.8 A6 6 0 0 1 16 16 c-3 0 -5 -2 -8 -2 a6 6 0 0 0 -4 1.528") } }
    /** Lucide `flame` */
    val Flame: ImageVector by lazy { icon("Flame") { s("M12 3 q1 4 4 6.5 t3 5.5 a1 1 0 0 1 -14 0 a5 5 0 0 1 1 -3 a1 1 0 0 0 5 0 c0 -2 -1.5 -3 -1.5 -5 q0 -2 2.5 -4") } }
    /** Lucide `footprints` */
    val Footprints: ImageVector by lazy { icon("Footprints") { s("M4 16 v-2.38 C4 11.5 2.97 10.5 3 8 c0.03 -2.72 1.49 -6 4.5 -6 C9.37 2 10 3.8 10 5.5 c0 3.11 -2 5.66 -2 8.68 V16 a2 2 0 1 1 -4 0 Z"); s("M20 20 v-2.38 c0 -2.12 1.03 -3.12 1 -5.62 c-0.03 -2.72 -1.49 -6 -4.5 -6 C14.63 6 14 7.8 14 9.5 c0 3.11 2 5.66 2 8.68 V20 a2 2 0 1 0 4 0 Z"); s("M16 17 h4"); s("M4 13 h4") } }
    /** Lucide `git-fork` */
    val GitFork: ImageVector by lazy { icon("GitFork") { s("M9 18 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0"); s("M3 6 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0"); s("M15 6 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0"); s("M18 9 v2 c0 0.6 -0.4 1 -1 1 H7 c-0.6 0 -1 -0.4 -1 -1 V9"); s("M12 12 v3") } }
    /** Lucide `graduation-cap` */
    val GraduationCap: ImageVector by lazy { icon("GraduationCap") { s("M21.42 10.922 a1 1 0 0 0 -0.019 -1.838 L12.83 5.18 a2 2 0 0 0 -1.66 0 L2.6 9.08 a1 1 0 0 0 0 1.832 l8.57 3.908 a2 2 0 0 0 1.66 0 z"); s("M22 10 v6"); s("M6 12.5 V16 a6 3 0 0 0 12 0 v-3.5") } }
    /** Lucide `layout-grid` */
    val Grid: ImageVector by lazy { icon("Grid") { s("M4 3 h5 a1 1 0 0 1 1 1 v5 a1 1 0 0 1 -1 1 h-5 a1 1 0 0 1 -1 -1 v-5 a1 1 0 0 1 1 -1 z"); s("M15 3 h5 a1 1 0 0 1 1 1 v5 a1 1 0 0 1 -1 1 h-5 a1 1 0 0 1 -1 -1 v-5 a1 1 0 0 1 1 -1 z"); s("M15 14 h5 a1 1 0 0 1 1 1 v5 a1 1 0 0 1 -1 1 h-5 a1 1 0 0 1 -1 -1 v-5 a1 1 0 0 1 1 -1 z"); s("M4 14 h5 a1 1 0 0 1 1 1 v5 a1 1 0 0 1 -1 1 h-5 a1 1 0 0 1 -1 -1 v-5 a1 1 0 0 1 1 -1 z") } }
    /** Lucide `grip-horizontal` */
    val GripHorizontal: ImageVector by lazy { icon("GripHorizontal") { s("M11 9 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0"); s("M18 9 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0"); s("M4 9 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0"); s("M11 15 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0"); s("M18 15 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0"); s("M4 15 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0") } }
    /** Lucide `hard-drive` */
    val HardDrive: ImageVector by lazy { icon("HardDrive") { s("M10 16 h0.01"); s("M2.212 11.577 a2 2 0 0 0 -0.212 0.896 V18 a2 2 0 0 0 2 2 h16 a2 2 0 0 0 2 -2 v-5.527 a2 2 0 0 0 -0.212 -0.896 L18.55 5.11 A2 2 0 0 0 16.76 4 H7.24 a2 2 0 0 0 -1.79 1.11 z"); s("M21.946 12.013 H2.054"); s("M6 16 h0.01") } }
    /** Lucide `heart` */
    val Heart: ImageVector by lazy { icon("Heart") { s("M2 9.5 a5.5 5.5 0 0 1 9.591 -3.676 a0.56 0.56 0 0 0 0.818 0 A5.49 5.49 0 0 1 22 9.5 c0 2.29 -1.5 4 -3 5.5 l-5.492 5.313 a2 2 0 0 1 -3 0.019 L5 15 c-1.5 -1.5 -3 -3.2 -3 -5.5") } }
    /** Tabler `heart` (filled) */
    val HeartFilled: ImageVector by lazy { icon("HeartFilled") { f("M6.979 3.074 a6 6 0 0 1 4.988 1.425 l0.037 0.033 l0.034 -0.03 a6 6 0 0 1 4.733 -1.44 l0.246 0.036 a6 6 0 0 1 3.364 10.008 l-0.18 0.185 l-0.048 0.041 l-7.45 7.379 a1 1 0 0 1 -1.313 0.082 l-0.094 -0.082 l-7.493 -7.422 a6 6 0 0 1 3.176 -10.215 z") } }
    /** Lucide `heart-pulse` */
    val HeartPulse: ImageVector by lazy { icon("HeartPulse") { s("M2 9.5 a5.5 5.5 0 0 1 9.591 -3.676 a0.56 0.56 0 0 0 0.818 0 A5.49 5.49 0 0 1 22 9.5 c0 2.29 -1.5 4 -3 5.5 l-5.492 5.313 a2 2 0 0 1 -3 0.019 L5 15 c-1.5 -1.5 -3 -3.2 -3 -5.5"); s("M3.22 13 H9.5 l0.5 -1 l2 4.5 l2 -7 l1.5 3.5 h5.27") } }
    /** Tabler `helmet` */
    val Helmet: ImageVector by lazy { icon("Helmet") { s("M12 4 a9 9 0 0 1 5.656 16 h-11.312 a9 9 0 0 1 5.656 -16"); s("M20 9 h-8.8 a1 1 0 0 0 -0.968 1.246 c0.507 2 1.596 3.418 3.268 4.254 c2 1 4.333 1.5 7 1.5") } }
    /** Lucide `circle-question-mark` */
    val Help: ImageVector by lazy { icon("Help") { s("M2 12 a10 10 0 1 0 20 0 a10 10 0 1 0 -20 0"); s("M9.09 9 a3 3 0 0 1 5.83 1 c0 2 -3 3 -3 3"); s("M12 17 h0.01") } }
    /** Lucide `rotate-ccw-clock` */
    val History: ImageVector by lazy { icon("History") { s("M3 12 a9 9 0 1 0 9 -9 a9.75 9.75 0 0 0 -6.74 2.74 L3 8"); s("M3 3 v5 h5"); s("M12 7 v5 l4 2") } }
    /** Lucide `house` */
    val Home: ImageVector by lazy { icon("Home") { s("M15 21 v-8 a1 1 0 0 0 -1 -1 h-4 a1 1 0 0 0 -1 1 v8"); s("M3 10 a2 2 0 0 1 0.709 -1.528 l7 -6 a2 2 0 0 1 2.582 0 l7 6 A2 2 0 0 1 21 10 v9 a2 2 0 0 1 -2 2 H5 a2 2 0 0 1 -2 -2 z") } }
    /** Lucide `images` */
    val Images: ImageVector by lazy { icon("Images") { s("m22 11 l-1.296 -1.296 a2.4 2.4 0 0 0 -3.408 0 L11 16"); s("M4 8 a2 2 0 0 0 -2 2 v10 a2 2 0 0 0 2 2 h10 a2 2 0 0 0 2 -2"); sf("M12 7 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0"); s("M10 2 h10 a2 2 0 0 1 2 2 v10 a2 2 0 0 1 -2 2 h-10 a2 2 0 0 1 -2 -2 v-10 a2 2 0 0 1 2 -2 z") } }
    /** Lucide `info` */
    val Info: ImageVector by lazy { icon("Info") { s("M2 12 a10 10 0 1 0 20 0 a10 10 0 1 0 -20 0"); s("M12 16 v-4"); s("M12 8 h0.01") } }
    /** Lucide `key-round` */
    val Key: ImageVector by lazy { icon("Key") { s("M2.586 17.414 A2 2 0 0 0 2 18.828 V21 a1 1 0 0 0 1 1 h3 a1 1 0 0 0 1 -1 v-1 a1 1 0 0 1 1 -1 h1 a1 1 0 0 0 1 -1 v-1 a1 1 0 0 1 1 -1 h0.172 a2 2 0 0 0 1.414 -0.586 l0.814 -0.814 a6.5 6.5 0 1 0 -4 -4 z"); sf("M16 7.5 a0.5 0.5 0 1 0 1 0 a0.5 0.5 0 1 0 -1 0") } }
    /** Lucide `link` */
    val Link: ImageVector by lazy { icon("Link") { s("M10 13 a5 5 0 0 0 7.54 0.54 l3 -3 a5 5 0 0 0 -7.07 -7.07 l-1.72 1.71"); s("M14 11 a5 5 0 0 0 -7.54 -0.54 l-3 3 a5 5 0 0 0 7.07 7.07 l1.71 -1.71") } }
    /** Lucide `unlink` */
    val LinkOff: ImageVector by lazy { icon("LinkOff") { s("m18.84 12.25 l1.72 -1.71 h-0.02 a5.004 5.004 0 0 0 -0.12 -7.07 a5.006 5.006 0 0 0 -6.95 0 l-1.72 1.71"); s("m5.17 11.75 l-1.71 1.71 a5.004 5.004 0 0 0 0.12 7.07 a5.006 5.006 0 0 0 6.95 0 l1.71 -1.71"); s("M8 2 L8 5"); s("M2 8 L5 8"); s("M16 19 L16 22"); s("M19 16 L22 16") } }
    /** Lucide `list` */
    val List: ImageVector by lazy { icon("List") { s("M3 5 h0.01"); s("M3 12 h0.01"); s("M3 19 h0.01"); s("M8 5 h13"); s("M8 12 h13"); s("M8 19 h13") } }
    /** Lucide `lock` */
    val Lock: ImageVector by lazy { icon("Lock") { s("M5 11 h14 a2 2 0 0 1 2 2 v7 a2 2 0 0 1 -2 2 h-14 a2 2 0 0 1 -2 -2 v-7 a2 2 0 0 1 2 -2 z"); s("M7 11 V7 a5 5 0 0 1 10 0 v4") } }
    /** Lucide `map-pin` */
    val MapPin: ImageVector by lazy { icon("MapPin") { s("M20 10 c0 4.993 -5.539 10.193 -7.399 11.799 a1 1 0 0 1 -1.202 0 C9.539 20.193 4 14.993 4 10 a8 8 0 0 1 16 0"); s("M9 10 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0") } }
    /** Lucide `map-pin-off` */
    val MapPinOff: ImageVector by lazy { icon("MapPinOff") { s("M12.75 7.09 a3 3 0 0 1 2.16 2.16"); s("M17.072 17.072 c-1.634 2.17 -3.527 3.912 -4.471 4.727 a1 1 0 0 1 -1.202 0 C9.539 20.193 4 14.993 4 10 a8 8 0 0 1 1.432 -4.568"); s("m2 2 l20 20"); s("M8.475 2.818 A8 8 0 0 1 20 10 c0 1.183 -0.31 2.377 -0.81 3.533"); s("M9.13 9.13 a3 3 0 0 0 3.74 3.74") } }
    /** Lucide `moon` */
    val Moon: ImageVector by lazy { icon("Moon") { s("M20.985 12.486 a9 9 0 1 1 -9.473 -9.472 c0.405 -0.022 0.617 0.46 0.402 0.803 a6 6 0 0 0 8.268 8.268 c0.344 -0.215 0.825 -0.004 0.803 0.401") } }
    /** Lucide `mountain` */
    val Mountain: ImageVector by lazy { icon("Mountain") { s("m8 3 l4 8 l5 -5 l5 15 H2 L8 3 z") } }
    /** Lucide `square-pen` */
    val NewChat: ImageVector by lazy { icon("NewChat") { s("M12 3 H5 a2 2 0 0 0 -2 2 v14 a2 2 0 0 0 2 2 h14 a2 2 0 0 0 2 -2 v-7"); s("M18.375 2.625 a1 1 0 0 1 3 3 l-9.013 9.014 a2 2 0 0 1 -0.853 0.505 l-2.873 0.84 a0.5 0.5 0 0 1 -0.62 -0.62 l0.84 -2.873 a2 2 0 0 1 0.506 -0.852 z") } }
    /** Lucide `notepad-text` */
    val NotepadText: ImageVector by lazy { icon("NotepadText") { s("M8 2 v4"); s("M12 2 v4"); s("M16 2 v4"); s("M6 4 h12 a2 2 0 0 1 2 2 v14 a2 2 0 0 1 -2 2 h-12 a2 2 0 0 1 -2 -2 v-14 a2 2 0 0 1 2 -2 z"); s("M8 10 h6"); s("M8 14 h8"); s("M8 18 h5") } }
    /** Tabler `player-play` (filled) */
    val Play: ImageVector by lazy { icon("Play") { f("M6 4 v16 a1 1 0 0 0 1.524 0.852 l13 -8 a1 1 0 0 0 0 -1.704 l-13 -8 a1 1 0 0 0 -1.524 0.852 z") } }
    /** Lucide `radio` */
    val Radio: ImageVector by lazy { icon("Radio") { s("M16.247 7.761 a6 6 0 0 1 0 8.478"); s("M19.075 4.933 a10 10 0 0 1 0 14.134"); s("M4.925 19.067 a10 10 0 0 1 0 -14.134"); s("M7.753 16.239 a6 6 0 0 1 0 -8.478"); s("M10 12 a2 2 0 1 0 4 0 a2 2 0 1 0 -4 0") } }
    /** Lucide `refresh-cw` */
    val Refresh: ImageVector by lazy { icon("Refresh") { s("M3 12 a9 9 0 0 1 9 -9 a9.75 9.75 0 0 1 6.74 2.74 L21 8"); s("M21 3 v5 h-5"); s("M21 12 a9 9 0 0 1 -9 9 a9.75 9.75 0 0 1 -6.74 -2.74 L3 16"); s("M8 16 H3 v5") } }
    /** Lucide `utensils` */
    val Restaurant: ImageVector by lazy { icon("Restaurant") { s("M3 2 v7 c0 1.1 0.9 2 2 2 h4 a2 2 0 0 0 2 -2 V2"); s("M7 2 v20"); s("M21 15 V2 a5 5 0 0 0 -5 5 v6 c0 1.1 0.9 2 2 2 h3 Z m0 0 v7") } }
    /** Lucide `rocket` */
    val Rocket: ImageVector by lazy { icon("Rocket") { s("M12 15 v5 s3.03 -0.55 4 -2 c1.08 -1.62 0 -5 0 -5"); s("M4.5 16.5 c-1.5 1.26 -2 5 -2 5 s3.74 -0.5 5 -2 c0.71 -0.84 0.7 -2.13 -0.09 -2.91 a2.18 2.18 0 0 0 -2.91 -0.09"); s("M9 12 a22 22 0 0 1 2 -3.95 A12.88 12.88 0 0 1 22 2 c0 2.72 -0.78 7.5 -6 11 a22.4 22.4 0 0 1 -4 2 z"); s("M9 12 H4 s0.55 -3.03 2 -4 c1.62 -1.08 5 0.05 5 0.05") } }
    /** Lucide `rows-3` */
    val Rows: ImageVector by lazy { icon("Rows") { s("M5 3 h14 a2 2 0 0 1 2 2 v14 a2 2 0 0 1 -2 2 h-14 a2 2 0 0 1 -2 -2 v-14 a2 2 0 0 1 2 -2 z"); s("M21 9 H3"); s("M21 15 H3") } }
    /** Tabler `run` */
    val Run: ImageVector by lazy { icon("Run") { s("M11.007 5 a2 2 0 1 0 4 0 a2 2 0 1 0 -4 0"); s("M4 17 l5 1 l0.75 -1.5"); s("M15 21 v-4 l-4 -3 l1 -6"); s("M7 12 v-3 l5 -1 l3 3 l3 1") } }
    /** Lucide `search` */
    val Search: ImageVector by lazy { icon("Search") { s("m21 21 l-4.34 -4.34"); s("M3 11 a8 8 0 1 0 16 0 a8 8 0 1 0 -16 0") } }
    /** Lucide `send-horizontal` */
    val Send: ImageVector by lazy { icon("Send") { s("M3.714 3.048 a0.498 0.498 0 0 0 -0.683 0.627 l2.843 7.627 a2 2 0 0 1 0 1.396 l-2.842 7.627 a0.498 0.498 0 0 0 0.682 0.627 l18 -8.5 a0.5 0.5 0 0 0 0 -0.904 z"); s("M6 12 h16") } }
    /** Lucide `server` */
    val Server: ImageVector by lazy { icon("Server") { s("M4 2 h16 a2 2 0 0 1 2 2 v4 a2 2 0 0 1 -2 2 h-16 a2 2 0 0 1 -2 -2 v-4 a2 2 0 0 1 2 -2 z"); s("M4 14 h16 a2 2 0 0 1 2 2 v4 a2 2 0 0 1 -2 2 h-16 a2 2 0 0 1 -2 -2 v-4 a2 2 0 0 1 2 -2 z"); s("M6 6 L6.01 6"); s("M6 18 L6.01 18") } }
    /** Lucide `settings` */
    val Settings: ImageVector by lazy { icon("Settings") { s("M9.671 4.136 a2.34 2.34 0 0 1 4.659 0 a2.34 2.34 0 0 0 3.319 1.915 a2.34 2.34 0 0 1 2.33 4.033 a2.34 2.34 0 0 0 0 3.831 a2.34 2.34 0 0 1 -2.33 4.033 a2.34 2.34 0 0 0 -3.319 1.915 a2.34 2.34 0 0 1 -4.659 0 a2.34 2.34 0 0 0 -3.32 -1.915 a2.34 2.34 0 0 1 -2.33 -4.033 a2.34 2.34 0 0 0 0 -3.831 A2.34 2.34 0 0 1 6.35 6.051 a2.34 2.34 0 0 0 3.319 -1.915"); s("M9 12 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0") } }
    /** Lucide `shirt` */
    val Shirt: ImageVector by lazy { icon("Shirt") { s("M20.38 3.46 L16 2 a4 4 0 0 1 -8 0 L3.62 3.46 a2 2 0 0 0 -1.34 2.23 l0.58 3.47 a1 1 0 0 0 0.99 0.84 H6 v10 c0 1.1 0.9 2 2 2 h8 a2 2 0 0 0 2 -2 V10 h2.15 a1 1 0 0 0 0.99 -0.84 l0.58 -3.47 a2 2 0 0 0 -1.34 -2.23 z") } }
    /** Lucide `smartphone` */
    val Smartphone: ImageVector by lazy { icon("Smartphone") { s("M7 2 h10 a2 2 0 0 1 2 2 v16 a2 2 0 0 1 -2 2 h-10 a2 2 0 0 1 -2 -2 v-16 a2 2 0 0 1 2 -2 z"); s("M12 18 h0.01") } }
    /** Lucide `sparkles` */
    val Sparkles: ImageVector by lazy { icon("Sparkles") { s("M11.017 2.814 a1 1 0 0 1 1.966 0 l1.051 5.558 a2 2 0 0 0 1.594 1.594 l5.558 1.051 a1 1 0 0 1 0 1.966 l-5.558 1.051 a2 2 0 0 0 -1.594 1.594 l-1.051 5.558 a1 1 0 0 1 -1.966 0 l-1.051 -5.558 a2 2 0 0 0 -1.594 -1.594 l-5.558 -1.051 a1 1 0 0 1 0 -1.966 l5.558 -1.051 a2 2 0 0 0 1.594 -1.594 z"); s("M20 2 v4"); s("M22 4 h-4"); s("M2 20 a2 2 0 1 0 4 0 a2 2 0 1 0 -4 0") } }
    /** Lucide `star` */
    val Star: ImageVector by lazy { icon("Star") { s("M11.525 2.295 a0.53 0.53 0 0 1 0.95 0 l2.31 4.679 a2.123 2.123 0 0 0 1.595 1.16 l5.166 0.756 a0.53 0.53 0 0 1 0.294 0.904 l-3.736 3.638 a2.123 2.123 0 0 0 -0.611 1.878 l0.882 5.14 a0.53 0.53 0 0 1 -0.771 0.56 l-4.618 -2.428 a2.122 2.122 0 0 0 -1.973 0 L6.396 21.01 a0.53 0.53 0 0 1 -0.77 -0.56 l0.881 -5.139 a2.122 2.122 0 0 0 -0.611 -1.879 L2.16 9.795 a0.53 0.53 0 0 1 0.294 -0.906 l5.165 -0.755 a2.122 2.122 0 0 0 1.597 -1.16 z") } }
    /** Lucide `arrow-down-up` */
    val SwapVertical: ImageVector by lazy { icon("SwapVertical") { s("m3 16 l4 4 l4 -4"); s("M7 20 V4"); s("m21 8 l-4 -4 l-4 4"); s("M17 4 v16") } }
    /** Lucide `waves-horizontal` */
    val Swim: ImageVector by lazy { icon("Swim") { s("M2 12 q2.5 2 5 0 t5 0 t5 0 t5 0"); s("M2 19 q2.5 2 5 0 t5 0 t5 0 t5 0"); s("M2 5 q2.5 2 5 0 t5 0 t5 0 t5 0") } }
    /** Lucide `tag` */
    val Tag: ImageVector by lazy { icon("Tag") { s("M12.586 2.586 A2 2 0 0 0 11.172 2 H4 a2 2 0 0 0 -2 2 v7.172 a2 2 0 0 0 0.586 1.414 l8.704 8.704 a2.426 2.426 0 0 0 3.42 0 l6.58 -6.58 a2.426 2.426 0 0 0 0 -3.42 z"); sf("M7 7.5 a0.5 0.5 0 1 0 1 0 a0.5 0.5 0 1 0 -1 0") } }
    /** Lucide `terminal` */
    val Terminal: ImageVector by lazy { icon("Terminal") { s("M12 19 h8"); s("m4 17 l6 -6 l-6 -6") } }
    /** Lucide `trophy` */
    val Trophy: ImageVector by lazy { icon("Trophy") { s("M10 14.66 V17 a1 1 0 0 1 -1 1 a2 2 0 0 0 -2 2 v2"); s("M14 14.66 V17 a1 1 0 0 0 1 1 a2 2 0 0 1 2 2 v2"); s("M17.916 10 H19.5 A2.5 2.5 0 0 0 22 7.5 V5 a1 1 0 0 0 -1 -1 h-3"); s("M4 22 h16"); s("M6 9 a6 6 0 0 0 12 0 V3 a1 1 0 0 0 -1 -1 H7 a1 1 0 0 0 -1 1 z"); s("M6.084 10 H4.5 A2.5 2.5 0 0 1 2 7.5 V5 a1 1 0 0 1 1 -1 h3") } }
    /** Lucide `tv-minimal-play` */
    val TvPlay: ImageVector by lazy { icon("TvPlay") { s("M15.033 9.44 a0.647 0.647 0 0 1 0 1.12 l-4.065 2.352 a0.645 0.645 0 0 1 -0.968 -0.56 V7.648 a0.645 0.645 0 0 1 0.967 -0.56 z"); s("M7 21 h10"); s("M4 3 h16 a2 2 0 0 1 2 2 v10 a2 2 0 0 1 -2 2 h-16 a2 2 0 0 1 -2 -2 v-10 a2 2 0 0 1 2 -2 z") } }
    /** Lucide `video` */
    val Video: ImageVector by lazy { icon("Video") { s("m16 13 l5.223 3.482 a0.5 0.5 0 0 0 0.777 -0.416 V7.87 a0.5 0.5 0 0 0 -0.752 -0.432 L16 10.5"); s("M4 6 h10 a2 2 0 0 1 2 2 v8 a2 2 0 0 1 -2 2 h-10 a2 2 0 0 1 -2 -2 v-8 a2 2 0 0 1 2 -2 z") } }
    /** Tabler `walk` */
    val Walk: ImageVector by lazy { icon("Walk") { s("M12 4 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0"); s("M7 21 l3 -4"); s("M16 21 l-2 -4 l-3 -3 l1 -6"); s("M6 12 l2 -3 l4 -1 l3 3 l3 1") } }
    /** Lucide `triangle-alert` */
    val Warning: ImageVector by lazy { icon("Warning") { s("m21.73 18 l-8 -14 a2 2 0 0 0 -3.48 0 l-8 14 A2 2 0 0 0 4 21 h16 a2 2 0 0 0 1.73 -3"); s("M12 9 v4"); s("M12 17 h0.01") } }
    /** Tabler `yoga` */
    val Yoga: ImageVector by lazy { icon("Yoga") { s("M4 20 h4 l1.5 -3"); s("M17 20 l-1 -5 h-5 l1 -7"); s("M4 10 l4 -1 l4 -1 l4 1.5 l4 1.5"); s("M10.007 5 a2 2 0 1 0 4 0 a2 2 0 1 0 -4 0") } }
    /** Lucide `weight` */
    val Scale: ImageVector by lazy { icon("Scale") { s("M9 5 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0"); s("M6.5 8 a2 2 0 0 0 -1.905 1.46 L2.1 18.5 A2 2 0 0 0 4 21 h16 a2 2 0 0 0 1.925 -2.54 L19.4 9.5 A2 2 0 0 0 17.48 8 Z") } }
    /** Lucide `thermometer` */
    val Thermometer: ImageVector by lazy { icon("Thermometer") { s("M14 4 v10.54 a4 4 0 1 1 -4 0 V4 a2 2 0 0 1 4 0 Z") } }
    /** Lucide `glass-water` */
    val GlassWater: ImageVector by lazy { icon("GlassWater") { s("M5.116 4.104 A1 1 0 0 1 6.11 3 h11.78 a1 1 0 0 1 0.994 1.105 L17.19 20.21 A2 2 0 0 1 15.2 22 H8.8 a2 2 0 0 1 -2 -1.79 Z"); s("M6 12 a5 5 0 0 1 6 0 a5 5 0 0 0 6 0") } }
    /** Lucide `gauge` */
    val Gauge: ImageVector by lazy { icon("Gauge") { s("m12 14 l4 -4"); s("M3.34 19 a10 10 0 1 1 17.32 0") } }
    /** Lucide `sunrise` */
    val Sunrise: ImageVector by lazy { icon("Sunrise") { s("M12 2 v8"); s("m4.93 10.93 l1.41 1.41"); s("M2 18 h2"); s("M20 18 h2"); s("m19.07 10.93 l-1.41 1.41"); s("M22 22 H2"); s("m8 6 l4 -4 l4 4"); s("M16 18 a4 4 0 0 0 -8 0") } }
    /** Lucide `droplet` */
    val Droplet: ImageVector by lazy { icon("Droplet") { s("M12 22 a7 7 0 0 0 7 -7 c0 -2 -1 -3.9 -3 -5.5 s-3.5 -4 -4 -6.5 c-0.5 2.5 -2 4.9 -4 6.5 C6 11.1 5 13 5 15 a7 7 0 0 0 7 7 z") } }
    /** Lucide `wind` */
    val Wind: ImageVector by lazy { icon("Wind") { s("M12.8 19.6 A2 2 0 1 0 14 16 H2"); s("M17.5 8 a2.5 2.5 0 1 1 2 4 H2"); s("M9.8 4.4 A2 2 0 1 1 11 8 H2") } }
    /** Lucide `bone` */
    val Bone: ImageVector by lazy { icon("Bone") { s("M17 10 c0.7 -0.7 1.69 0 2.5 0 a2.5 2.5 0 1 0 0 -5 a0.5 0.5 0 0 1 -0.5 -0.5 a2.5 2.5 0 1 0 -5 0 c0 0.81 0.7 1.8 0 2.5 l-7 7 c-0.7 0.7 -1.69 0 -2.5 0 a2.5 2.5 0 0 0 0 5 c0.28 0 0.5 0.22 0.5 0.5 a2.5 2.5 0 1 0 5 0 c0 -0.81 -0.7 -1.8 0 -2.5 Z") } }
    /** Lucide `droplets` */
    val Droplets: ImageVector by lazy { icon("Droplets") { s("M7 16.3 c2.2 0 4 -1.83 4 -4.05 c0 -1.16 -0.57 -2.26 -1.71 -3.19 S7.29 6.75 7 5.3 c-0.29 1.45 -1.14 2.84 -2.29 3.76 S3 11.1 3 12.25 c0 2.22 1.8 4.05 4 4.05 z"); s("M12.56 6.6 A10.97 10.97 0 0 0 14 3.02 c0.5 2.5 2 4.9 4 6.5 s3 3.5 3 5.5 a6.98 6.98 0 0 1 -11.91 4.97") } }
    /** Lucide `thermometer-sun` */
    val ThermometerSun: ImageVector by lazy { icon("ThermometerSun") { s("M12 2 v2"); s("M12 8 a4 4 0 0 0 -1.645 7.647"); s("M2 12 h2"); s("M20 14.54 a4 4 0 1 1 -4 0 V4 a2 2 0 0 1 4 0 z"); s("m4.93 4.93 l1.41 1.41"); s("m6.34 17.66 l-1.41 1.41") } }
    /** Lucide `test-tube-diagonal` */
    val TestTube: ImageVector by lazy { icon("TestTube") { s("M21 7 L6.82 21.18 a2.83 2.83 0 0 1 -3.99 -0.01 a2.83 2.83 0 0 1 0 -4 L17 3"); s("m16 2 l6 6"); s("M12 16 H4") } }
    /** Tabler `heart-rate-monitor` */
    val HeartRateMonitor: ImageVector by lazy { icon("HeartRateMonitor") { s("M3 5 a1 1 0 0 1 1 -1 h16 a1 1 0 0 1 1 1 v10 a1 1 0 0 1 -1 1 h-16 a1 1 0 0 1 -1 -1 l0 -10"); s("M7 20 h10"); s("M9 16 v4"); s("M15 16 v4"); s("M7 10 h2 l2 3 l2 -6 l1 3 h3") } }
}

private val Ink = SolidColor(Color.Black)

private class IconBuilder(val builder: ImageVector.Builder) {
    fun s(d: String) = add(d, stroke = true, fill = false)
    fun f(d: String) = add(d, stroke = false, fill = true)
    fun sf(d: String) = add(d, stroke = true, fill = true)

    private fun add(d: String, stroke: Boolean, fill: Boolean) {
        builder.addPath(
            pathData = PathParser().parsePathString(d).toNodes(),
            fill = if (fill) Ink else null,
            stroke = if (stroke) Ink else null,
            strokeLineWidth = if (stroke) 2f else 0f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        )
    }
}

private inline fun icon(name: String, block: IconBuilder.() -> Unit): ImageVector {
    val builder = ImageVector.Builder(
        name = name,
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    IconBuilder(builder).block()
    return builder.build()
}
